version: "3.8"
services:
  python-runner:
    build: ./PythonRunnerMicroservice
    ports:
      - "8803:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    networks:
      - backend

  cpp-runner:
    build: ./CppRunnerMicroservice
    ports:
      - "8804:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    networks:
      - backend

  java-runner:
    build: ./JavaRunnerMicroservice
    ports:
      - "8805:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    networks:
      - backend

  python-tester:
    build: ./PythonUnittestMicroservice
    ports:
      - "8806:8000"
    networks:
      - backend
    env_file:
      - ./PythonUnittestMicroservice/.env

  cpp-tester:
    build: ./CppUnittestMicroservice
    ports:
      - "8807:8000"
    networks:
      - backend
    env_file:
      - ./CppUnittestMicroservice/.env

  java-tester:
    build: ./JavaUnittestMicroservice
    ports:
      - "8808:8000"
    networks:
      - backend
    env_file:
      - ./JavaUnittestMicroservice/.env

  pl-similarity:
    build: ./ScriptSimilarityMicroservice
    ports:
      - "8801:8000"
    networks:
      - backend

  nl-similarity:
    build: ./SimilarityMicroservice
    ports:
      - "8802:8000"
    networks:
      - backend

  gateway:
    build: ./Gateway
    ports:
      - "8800:8000"
    networks:
      - backend
    env_file:
      - ./Gateway/.env

networks:
  backend:
    driver: bridge